; ==================================================
; PlatformIO – Hühnerklappe ESP32-S3-DevKitC-1-N16R8
; ==================================================

[platformio]
boards_dir = boards

[env:esp32-s3-devkitc-1]
platform   = espressif32
board      = esp32-s3-devkitc-1-n16r8
framework  = arduino

monitor_speed = 115200
upload_speed  = 921600

board_build.flash_size  = 16MB
board_build.partitions  = partitions_16mb_ota.csv
board_build.filesystem  = littlefs

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=0
    -DHTTP_UPLOAD_BUFLEN=8192

lib_deps =
    adafruit/Adafruit VEML7700 Library
    adafruit/RTClib
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
